name: Obole
main: me.monnierant.obole.Donation
version: 3.0
description: Donation system.
author: Monnier Antoine, Trioxinz
commands:
  donationreload:
    description: Reloads the configuration file for the donation system.
    usage: /donationreload
permissions:
  Donation.Admin:
        description: Gives admin access to the donation system.